// <auto-generated />
using System;
using ControleMateriaisApi.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleMateriaisApi.Migrations
{
    [DbContext(typeof(AplicationContext))]
    partial class AplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("ControleMateriaisApi.Domain.ItemOrdemServico", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_item_ordem_servico");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_cadastro");

                    b.Property<int?>("IdMaterial")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_material");

                    b.Property<int?>("IdOs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_ordem_servico");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantidade");

                    b.HasKey("Id");

                    b.HasIndex("IdMaterial");

                    b.HasIndex("IdOs");

                    b.ToTable("item_ordem_servico", (string)null);
                });

            modelBuilder.Entity("ControleMateriaisApi.Domain.Material", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_material");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("UnidadeMedida")
                        .HasColumnType("TEXT")
                        .HasColumnName("unidade_medida");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.HasIndex("UnidadeMedida");

                    b.ToTable("materiais", (string)null);
                });

            modelBuilder.Entity("ControleMateriaisApi.Domain.OrdemServico", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_os");

                    b.Property<string>("Bairro")
                        .HasColumnType("TEXT")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasColumnType("TEXT")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasColumnType("TEXT")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasColumnType("TEXT")
                        .HasColumnName("complemento");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_cadastro");

                    b.Property<int>("IdPolo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_polo");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Logradouro")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER")
                        .HasColumnName("numero");

                    b.Property<int>("TipoOrdemDeServico")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tipo_ordem_servico");

                    b.HasKey("Id");

                    b.HasIndex("IdPolo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ordens_servico", (string)null);
                });

            modelBuilder.Entity("ControleMateriaisApi.Domain.Polo", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_polo");

                    b.Property<string>("Bairro")
                        .HasColumnType("TEXT")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasColumnType("TEXT")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasColumnType("TEXT")
                        .HasColumnName("cidade");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Logradouro")
                        .HasColumnType("TEXT")
                        .HasColumnName("logradouro");

                    b.Property<string>("NomePolo")
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_polo");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER")
                        .HasColumnName("numero");

                    b.Property<string>("Uf")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NomePolo");

                    b.ToTable("polos", (string)null);
                });

            modelBuilder.Entity("ControleMateriaisApi.Domain.Usuario", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_usuario");

                    b.Property<int?>("CodigoRecuperarSenha")
                        .HasColumnType("INTEGER")
                        .HasColumnName("codigo_senha");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<int?>("Perfil")
                        .HasColumnType("INTEGER")
                        .HasColumnName("perfil");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT")
                        .HasColumnName("senha");

                    b.HasKey("Id");

                    b.HasIndex("CodigoRecuperarSenha");

                    b.HasIndex("Email");

                    b.HasIndex("Nome");

                    b.HasIndex("Senha");

                    b.HasIndex("Senha", "Email");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ControleMateriaisApi.Domain.ItemOrdemServico", b =>
                {
                    b.HasOne("ControleMateriaisApi.Domain.Material", "Material")
                        .WithMany()
                        .HasForeignKey("IdMaterial");

                    b.HasOne("ControleMateriaisApi.Domain.OrdemServico", "OrdemServico")
                        .WithMany("ItensOrdemServico")
                        .HasForeignKey("IdOs");

                    b.Navigation("Material");

                    b.Navigation("OrdemServico");
                });

            modelBuilder.Entity("ControleMateriaisApi.Domain.OrdemServico", b =>
                {
                    b.HasOne("ControleMateriaisApi.Domain.Polo", "Polo")
                        .WithMany("OrdensDeServicos")
                        .HasForeignKey("IdPolo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleMateriaisApi.Domain.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario");

                    b.Navigation("Polo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControleMateriaisApi.Domain.OrdemServico", b =>
                {
                    b.Navigation("ItensOrdemServico");
                });

            modelBuilder.Entity("ControleMateriaisApi.Domain.Polo", b =>
                {
                    b.Navigation("OrdensDeServicos");
                });
#pragma warning restore 612, 618
        }
    }
}
